- name: nginxインストール
  become: yes
  apt:
    pkg: nginx
    update_cache: yes
- name: http設定ファイル設置
  become: yes
  template:
    src: ../templates/{{ nginx.http_conf_name }}
    dest: /etc/nginx/conf.d/{{ nginx.server_name }}.conf
- name: サービス再起動
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes